### ISSUE TITLE
ENZYMES data differs from the source

### ISSUE THREAD

**Issue by se-ok** [BorgwardtLab/WWL#1]
Hi,

While experimenting with your code I noticed that the .gml files does not exactly match the original TU ENZYMES dataset here:
https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets

The total nodes in the original is 19,580 while here they add up to 19,474.

These are the graphs with differing number of nodes :
#37, #117, #294, #295, #296, #500, #540, #599

As I have not found a detailed explanation of how the dataset is constructed, I wonder if there were some pre-processing to cut the nodes or it is merely from a mistake.

Thank you so much for providing a running implementation of your valuable research.

**Comment by mtog** [comment]
Hi se-ok,

Thanks for pointing that out. We indeed processed the data set to remove isolated nodes in the graphs. Let me know if this answers your question.

Cheers!

**Comment by se-ok** [comment]
Hi Dr. Togninalli,

Thank you so much for your response. It clears up my question.

**Comment by Anwar-Said** [comment]
Hi, 
I'm having trouble reproducing the results on the PTC, NCI1, and PROTEINS datasets. I have converted TU datasets to the required GML format. Each graph appears to have been constructed appropriately, with each node properly labeled. I was able to reproduce results on Mutag and Enzymes while regenerating these datasets with my script, but I can't reproduce results on other datasets for some reason. I would appreciate it if you could share more information about how these datasets were preprocessed. I have also removed the isolated nodes but no luck. As an example, I have attached the gml of the first graph of NCI1 dataset.  Thanks
[000.zip](https://github.com/BorgwardtLab/WWL/files/8758255/000.zip)
.
