### ISSUE TITLE
Understandings of WWL 

### ISSUE THREAD

**Issue by Jarvis-K** [BorgwardtLab/WWL#2]
After reading the WWL paper, I do not quite understand the WWL kernel, can u please help me with the following questions?
1. the wwl kernel is calculated among graphs. however, the graph classification usually take the single graph embedding as input, how the wwl kernel update the single graph embedding?
2. For a set of graphs, there is no edge between two graphs, how can the wwl  calc the Laplacian matrix?

It will be a great help for having your reply.

**Comment by mtog** [comment]
Hi Jarvis,

Thank you for your interest. Here are some answers to your questions:

1. WWL is a [kernel-based method](https://en.wikipedia.org/wiki/Kernel_method), meaning that the we do not create an explicit representation of the graph but rather directly compute the inner product of such representations. In practice, this means that the output of the main algorithm is a kernel (i.e. similarity) matrix between a _set_ of graphs which is then fed into a classifier designed to work with such data. At test time, you can infer on new graphs by computing their kernel value w.r.t the training samples in a similar fashion. What might lead to confusion is that, to obtain **graph-level similarities**, we generate _node-level_ embeddings and then use them to compute a Wasserstein distance between the graphs which is in turn transformed into a kernel value.
2. We do not calculate the Laplacian matrix between disjunct graphs but rather compute the pairwise kernel value between each pair of graphs. 

Let me know if this answers your questions.

**Comment by ljmartin** [comment]
hi @mtog - in this case, can the kernel values between the test instances and the training instances be calculated without generating the full pairwise kernel matrix of all instances? It looks like `wwl` takes only a single set of graphs and outputs a full kernel matrix.

With large numbers of test instances, there would be an enormous number of kernels calculated between test instances, even though these values don't get used in (for example) an SVM.
